agent:
  name: anomalib_inference
  description: "Agent to perform torch classificaction inference and draw resulting label."

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: AnomalibTorchInference
  class_name: AnomalibTorchInference
  template_input: InputTemplate
  attributes:
    model_path: "artifacts/exported_models/weights/torch/model.pt"
    device: "cuda"

- template_name: BBoxDrawer
  class_name: BBoxDrawer
  template_input:  AnomalibTorchInference
  attributes:
    randomized_color: false
    draw_classification_label: false

- template_name: SegmentationMaskDrawer
  class_name: SegmentationMaskDrawer
  template_input: BBoxDrawer
  attributes:
    overwrite: true
    randomized_color: false
    draw_classification_label: false
